version: 1
jobs:
  compile:
    image: node
    script:
      - npm install truffle
      - ./node_modules/.bin/truffle compile
  test:
    image: node
    script:
      - npm install truffle
      - ./node_modules/.bin/truffle test
stages:
  - pipeline:
      jobs:
        - compile
        - test
